# Generated by Django 5.1.3 on 2024-12-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageHistory',
        ),
    ]
